[project]
name = "distance-transforms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "juliacall>=0.9.24",
    "numpy>=2.2.3",
    "pytest>=8.3.5",
    "torch>=2.6.0",
]
